export const pageRoutes = {
    '/': 'home',
    home: '/',
    areas: '/areas',
    contact: '/contact',
};

const regionsObj = [
    { Ain: 'Ain' },
    { Aisne: 'Aisne' },
    { Allier: 'Allier' },
    { 'Alpes-de-Haute-Provence': 'Alpes-de-Haute-Provence' },
    { 'Hautes-Alpes': 'Hautes-Alpes' },
    { 'Alpes-Maritimes': 'Alpes-Maritimes' },
    { Ardèche: 'Ardèche' },
    { Ardennes: 'Ardennes' },
    { Ariège: 'Ariège' },
    { Aube: 'Aube' },
    { Aude: 'Aude' },
    { Aveyron: 'Aveyron' },
    { 'Bouches-du-Rhône': 'Bouches-du-Rhône' },
    { Calvados: 'Calvados' },
    { Cantal: 'Cantal' },
    { Charente: 'Charente' },
    { 'Charente-Maritime': 'Charente-Maritime' },
    { Cher: 'Cher' },
    { Corrèze: 'Corrèze' },
    { 'Côte-d’Or': 'Côte-d’Or' },
    { 'Côtes-d’Armor': 'Côtes-d’Armor' },
    { Creuse: 'Creuse' },
    { Dordogne: 'Dordogne' },
    { Doubs: 'Doubs' },
    { Drôme: 'Drôme' },
    { Eure: 'Eure' },
    { 'Eure-et-Loir': 'Eure-et-Loir' },
    { Finistère: 'Finistère' },
    { 'Corse-du-Sud': 'Corse-du-Sud' },
    { 'Haute-Corse': 'Haute-Corse' },
    { Gard: 'Gard' },
    { 'Haute-Garonne': 'Haute-Garonne' },
    { Gers: 'Gers' },
    { Gironde: 'Gironde' },
    { Hérault: 'Hérault' },
    { 'Ille-et-Vilaine': 'Ille-et-Vilaine' },
    { Indre: 'Indre' },
    { 'Indre-et-Loire': 'Indre-et-Loire' },
    { Isère: 'Isère' },
    { Jura: 'Jura' },
    { Landes: 'Landes' },
    { 'Loir-et-Cher': 'Loir-et-Cher' },
    { Loire: 'Loire' },
    { 'Haute-Loire': 'Haute-Loire' },
    { 'Loire-Atlantique': 'Loire-Atlantique' },
    { Loiret: 'Loiret' },
    { Lot: 'Lot' },
    { 'Lot-et-Garonne': 'Lot-et-Garonne' },
    { Lozère: 'Lozère' },
    { 'Maine-et-Loire': 'Maine-et-Loire' },
    { Manche: 'Manche' },
    { Marne: 'Marne' },
    { 'Haute-Marne': 'Haute-Marne' },
    { Mayenne: 'Mayenne' },
    { 'Meurthe-et-Moselle': 'Meurthe-et-Moselle' },
    { Meuse: 'Meuse' },
    { Morbihan: 'Morbihan' },
    { Moselle: 'Moselle' },
    { Nièvre: 'Nièvre' },
    { Nord: 'Nord' },
    { Oise: 'Oise' },
    { Orne: 'Orne' },
    { 'Pas-de-Calais': 'Pas-de-Calais' },
    { 'Puy-de-Dôme': 'Puy-de-Dôme' },
    { 'Pyrénées-Atlantiques': 'Pyrénées-Atlantiques' },
    { 'Hautes-Pyrénées': 'Hautes-Pyrénées' },
    { 'Pyrénées-Orientales': 'Pyrénées-Orientales' },
    { 'Bas-Rhin': 'Bas-Rhin' },
    { 'Haut-Rhin': 'Haut-Rhin' },
    { Rhône: 'Rhône' },
    { 'Haute-Saône': 'Haute-Saône' },
    { 'Saône-et-Loire': 'Saône-et-Loire' },
    { Sarthe: 'Sarthe' },
    { Savoie: 'Savoie' },
    { 'Haute-Savoie': 'Haute-Savoie' },
    { Paris: 'Paris' },
    { 'Seine-Maritime': 'Seine-Maritime' },
    { 'Seine-et-Marne': 'Seine-et-Marne' },
    { Yvelines: 'Yvelines' },
    { 'Deux-Sèvres': 'Deux-Sèvres' },
    { Somme: 'Somme' },
    { Tarn: 'Tarn' },
    { 'Tarn-et-Garonne': 'Tarn-et-Garonne' },
    { Var: 'Var' },
    { Vaucluse: 'Vaucluse' },
    { Vendée: 'Vendée' },
    { Vienne: 'Vienne' },
    { 'Haute-Vienne': 'Haute-Vienne' },
    { Vosges: 'Vosges' },
    { Yonne: 'Yonne' },
    { 'Territoire de Belfort': 'Territoire de Belfort' },
    { Essonne: 'Essonne' },
    { 'Hauts-de-Seine': 'Hauts-de-Seine' },
    { 'Seine-Saint-Denis': 'Seine-Saint-Denis' },
    { 'Val-de-Marne': 'Val-de-Marne' },
    { 'Val-d’Oise': 'Val-d’Oise' },
];

export const regions = [
    'Ain',
    'Aisne',
    'Allier',
    'Alpes-de-Haute-Provence',
    'Hautes-Alpes',
    'Alpes-Maritimes',
    'Ardèche',
    'Ardennes',
    'Ariège',
    'Aube',
    'Aude',
    'Aveyron',
    'Bouches-du-Rhône',
    'Calvados',
    'Cantal',
    'Charente',
    'Charente-Maritime',
    'Cher',
    'Corrèze',
    'Côte-d’Or',
    'Côtes-d’Armor',
    'Creuse',
    'Dordogne',
    'Doubs',
    'Drôme',
    'Eure',
    'Eure-et-Loir',
    'Finistère',
    'Corse-du-Sud',
    'Haute-Corse',
    'Gard',
    'Haute-Garonne',
    'Gers',
    'Gironde',
    'Hérault',
    'Ille-et-Vilaine',
    'Indre',
    'Indre-et-Loire',
    'Isère',
    'Jura',
    'Landes',
    'Loir-et-Cher',
    'Loire',
    'Haute-Loire',
    'Loire-Atlantique',
    'Loiret',
    'Lot',
    'Lot-et-Garonne',
    'Lozère',
    'Maine-et-Loire',
    'Manche',
    'Marne',
    'Haute-Marne',
    'Mayenne',
    'Meurthe-et-Moselle',
    'Meuse',
    'Morbihan',
    'Moselle',
    'Nièvre',
    'Nord',
    'Oise',
    'Orne',
    'Pas-de-Calais',
    'Puy-de-Dôme',
    'Pyrénées-Atlantiques',
    'Hautes-Pyrénées',
    'Pyrénées-Orientales',
    'Bas-Rhin',
    'Haut-Rhin',
    'Rhône',
    'Haute-Saône',
    'Saône-et-Loire',
    'Sarthe',
    'Savoie',
    'Haute-Savoie',
    'Paris',
    'Seine-Maritime',
    'Seine-et-Marne',
    'Yvelines',
    'Deux-Sèvres',
    'Somme',
    'Tarn',
    'Tarn-et-Garonne',
    'Var',
    'Vaucluse',
    'Vendée',
    'Vienne',
    'Haute-Vienne',
    'Vosges',
    'Yonne',
    'Territoire de Belfort',
    'Essonne',
    'Hauts-de-Seine',
    'Seine-Saint-Denis',
    'Val-de-Marne',
    'Val-d’Oise',
];
